export enum AudioClipsEnum {
    Base_C1Collect = 'Base_C1Collect',
    Base_C1CollectHit = 'Base_C1CollectHit',
    Base_C1CollectHitAlarm = 'Base_C1CollectHitAlarm',
    Base_C1Hit01 = 'Base_C1Hit01',
    Base_C1Hit02 = 'Base_C1Hit02',
    Base_FeatureInitialCollect = 'Base_FeatureInitialCollect',
    Base_WildScoring = 'Base_WildScoring',
    BigWinHit = 'BigWinHit',
    BigWinPrediction = 'BigWinPrediction',
    Button_Spin = 'Button_Spin',
    Button_SpinReel = 'Button_SpinReel',
    Button_UI = 'Button_UI',
    DragonUp_C1Collect = 'DragonUp_C1Collect',
    DragonUp_C1CollectHit01 = 'DragonUp_C1CollectHit01',
    DragonUp_C2Collect = 'DragonUp_C2Collect',
    DragonUp_PercentCollect = 'DragonUp_PercentCollect',
    DragonUp_PercentCollect02 = 'DragonUp_PercentCollect02',
    DragonUp_PercentHit = 'DragonUp_PercentHit',
    DragonUp_RetriggerCollect = 'DragonUp_RetriggerCollect',
    DragonUp_RetriggerHit = 'DragonUp_RetriggerHit',
    FeatureSelection_BestChoice = 'FeatureSelection_BestChoice',
    FeatureSelection_Crowd = 'FeatureSelection_Crowd',
    Free_C1Collect = 'Free_C1Collect',
    Free_C1FireThrough = 'Free_C1FireThrough',
    Free_C1GrowUp = 'Free_C1GrowUp',
    Free_C1Hit01 = 'Free_C1Hit01',
    Free_WStack01 = 'Free_WStack01',
    Free_WStack02 = 'Free_WStack02',
    Free_Calculation = 'Free_Calculation',
    Free_ExpandWild = 'Free_ExpandWild',
    Free_Retrigger = 'Free_Retrigger',
    Result = 'Result',
    JP_GrandHit = 'JP_GrandHit',
    Mini_GemFall = 'Mini_GemFall',
    Mini_Expectation = 'Mini_Expectation',
    Mini_Open = 'Mini_Open',
    Mini_SymbolLocate = 'Mini_SymbolLocate',
    MiniEnd00 = 'MiniEnd00',
    MiniEnd00_ENG = 'MiniEnd00_ENG',
    MiniEnd00Multiple = 'MiniEnd00Multiple',
    MiniEnd01 = 'MiniEnd01',
    MiniEnd02 = 'MiniEnd02',
    MiniEnd03 = 'MiniEnd03',
    MiniHit01 = 'MiniHit01',
    MiniHit02 = 'MiniHit02',
    MiniHit03 = 'MiniHit03',
    MiniHit04 = 'MiniHit04',
    MiniCountdown01 = 'MiniCountdown01',
    MiniCountdown02 = 'MiniCountdown02',
    PrizePrediction = 'PrizePrediction',
    SpinStop01 = 'SpinStop01',
    SpinStop02 = 'SpinStop02',
    SpinStop03 = 'SpinStop03',
    SpinStop04 = 'SpinStop04',
    SpinStop05 = 'SpinStop05',

    JPResult_en = 'JPResult_en',
    JPResult_zh = 'JPResult_zh',
}

export enum BGMClipsEnum {
    BGM_Base = 'BGM_Base',
    BGM_BaseIdle = 'BGM_BaseIdle',
    BGM_DragonUp = 'BGM_DragonUp',
    BGM_FeatureSelection = 'BGM_FeatureSelection',
    BGM_FreeGame = 'BGM_FreeGame',
    BGM_Mini = 'BGM_Mini'
}

export enum ScoringClipsEnum {
    Scoring_Base = 'Scoring_Base',
    Scoring_BaseEnd = 'Scoring_BaseEnd',
    Scoring_Free = 'Scoring_Free',
    Scoring_FreeEnd = 'Scoring_FreeEnd',
    Scoring_JPWinEnd = 'Scoring_JPWinEnd',
    Scoring_JPWinIntro = 'Scoring_JPWinIntro',
    Scoring_JPWinLoop = 'Scoring_JPWinLoop',
    Scoring_Win01 = 'Scoring_Win01',
    Scoring_Win02 = 'Scoring_Win02',
    Scoring_Win03 = 'Scoring_Win03',
    Scoring_Win04 = 'Scoring_Win04'
}
export enum BaseScoringDuration {
    Scoring01 = 0.5,
    Scoring02 = 1,
    Scoring03 = 2,
    Scoring04 = 2,
    Scoring05 = 3,
    Scoring06 = 3,
    Scoring07 = 3,
    Scoring08 = 4,
    Scoring09 = 5,
    Scoring10 = 8,
    Scoring11 = 8,
    Scoring12 = 10,
    Scoring13 = 13,
    Scoring14 = 21,
    Scoring15 = 25,
    Scoring_Win01 = 14.5,
    Scoring_Win02 = 14.8,
    Scoring_Win03 = 23,
    Scoring_Win04 = 27.8
}

export enum QuickScoringDuration {
    Scoring_normal = 0,
    Scoring_BigWin = 1,
    Scoring_MegaWin = 1,
    Scoring_SuperWin = 1,
    Scoring_JumboWin = 1
}
